version: '3.4'

services:
  qin-guru:
    image: qin-guru
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      TOKEN: ${TOKEN}
      SERVER_ID: ${SERVER_ID}
      RATELIMIT_MAX_RPS: ${RATELIMIT_MAX_RPS}
    ports:
      - 8080:8080
